simpleServer.py fix to be able to start and to pass response delay time
In my case I had to modify your script to be able to run it on Python 2.6.9

1. The "from SimpleHTTPServer import SimpleHTTPRequestHandler"
Otherwise I get a 'AttributeError: 'module' object has no Attribute 'SimpleHTTPRequestHandler'

2. While giving both command line Options, the delay time gets a "TypeError: a float is required"
That's why I do a float() around